version: '3.8'

services:
  backend:
    build:
      context: ./backend_python
    container_name: dictionary_service
    ports:
      - "50051:50051"
  gateway:
    build:
      context: ./gateway
    container_name: api_gateway
    ports:
      - "8080:8080"
    depends_on:
      - backend
