# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dictionary_pb2 as dictionary__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in dictionary_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DictionaryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddWord = channel.unary_unary(
                '/DictionaryService/AddWord',
                request_serializer=dictionary__pb2.WordRequest.SerializeToString,
                response_deserializer=dictionary__pb2.WordResponse.FromString,
                _registered_method=True)
        self.GetAllWords = channel.unary_unary(
                '/DictionaryService/GetAllWords',
                request_serializer=dictionary__pb2.Empty.SerializeToString,
                response_deserializer=dictionary__pb2.WordList.FromString,
                _registered_method=True)


class DictionaryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddWord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllWords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DictionaryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddWord': grpc.unary_unary_rpc_method_handler(
                    servicer.AddWord,
                    request_deserializer=dictionary__pb2.WordRequest.FromString,
                    response_serializer=dictionary__pb2.WordResponse.SerializeToString,
            ),
            'GetAllWords': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllWords,
                    request_deserializer=dictionary__pb2.Empty.FromString,
                    response_serializer=dictionary__pb2.WordList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DictionaryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('DictionaryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DictionaryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddWord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DictionaryService/AddWord',
            dictionary__pb2.WordRequest.SerializeToString,
            dictionary__pb2.WordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllWords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DictionaryService/GetAllWords',
            dictionary__pb2.Empty.SerializeToString,
            dictionary__pb2.WordList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
