// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: dictionary.proto
#ifndef GRPC_dictionary_2eproto__INCLUDED
#define GRPC_dictionary_2eproto__INCLUDED

#include "dictionary.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

class DictionaryService final {
 public:
  static constexpr char const* service_full_name() {
    return "DictionaryService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status AddWord(::grpc::ClientContext* context, const ::WordRequest& request, ::WordResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::WordResponse>> AsyncAddWord(::grpc::ClientContext* context, const ::WordRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::WordResponse>>(AsyncAddWordRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::WordResponse>> PrepareAsyncAddWord(::grpc::ClientContext* context, const ::WordRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::WordResponse>>(PrepareAsyncAddWordRaw(context, request, cq));
    }
    virtual ::grpc::Status GetAllWords(::grpc::ClientContext* context, const ::Empty& request, ::WordList* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::WordList>> AsyncGetAllWords(::grpc::ClientContext* context, const ::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::WordList>>(AsyncGetAllWordsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::WordList>> PrepareAsyncGetAllWords(::grpc::ClientContext* context, const ::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::WordList>>(PrepareAsyncGetAllWordsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void AddWord(::grpc::ClientContext* context, const ::WordRequest* request, ::WordResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AddWord(::grpc::ClientContext* context, const ::WordRequest* request, ::WordResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetAllWords(::grpc::ClientContext* context, const ::Empty* request, ::WordList* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetAllWords(::grpc::ClientContext* context, const ::Empty* request, ::WordList* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::WordResponse>* AsyncAddWordRaw(::grpc::ClientContext* context, const ::WordRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::WordResponse>* PrepareAsyncAddWordRaw(::grpc::ClientContext* context, const ::WordRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::WordList>* AsyncGetAllWordsRaw(::grpc::ClientContext* context, const ::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::WordList>* PrepareAsyncGetAllWordsRaw(::grpc::ClientContext* context, const ::Empty& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status AddWord(::grpc::ClientContext* context, const ::WordRequest& request, ::WordResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::WordResponse>> AsyncAddWord(::grpc::ClientContext* context, const ::WordRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::WordResponse>>(AsyncAddWordRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::WordResponse>> PrepareAsyncAddWord(::grpc::ClientContext* context, const ::WordRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::WordResponse>>(PrepareAsyncAddWordRaw(context, request, cq));
    }
    ::grpc::Status GetAllWords(::grpc::ClientContext* context, const ::Empty& request, ::WordList* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::WordList>> AsyncGetAllWords(::grpc::ClientContext* context, const ::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::WordList>>(AsyncGetAllWordsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::WordList>> PrepareAsyncGetAllWords(::grpc::ClientContext* context, const ::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::WordList>>(PrepareAsyncGetAllWordsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void AddWord(::grpc::ClientContext* context, const ::WordRequest* request, ::WordResponse* response, std::function<void(::grpc::Status)>) override;
      void AddWord(::grpc::ClientContext* context, const ::WordRequest* request, ::WordResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetAllWords(::grpc::ClientContext* context, const ::Empty* request, ::WordList* response, std::function<void(::grpc::Status)>) override;
      void GetAllWords(::grpc::ClientContext* context, const ::Empty* request, ::WordList* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::WordResponse>* AsyncAddWordRaw(::grpc::ClientContext* context, const ::WordRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::WordResponse>* PrepareAsyncAddWordRaw(::grpc::ClientContext* context, const ::WordRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::WordList>* AsyncGetAllWordsRaw(::grpc::ClientContext* context, const ::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::WordList>* PrepareAsyncGetAllWordsRaw(::grpc::ClientContext* context, const ::Empty& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_AddWord_;
    const ::grpc::internal::RpcMethod rpcmethod_GetAllWords_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status AddWord(::grpc::ServerContext* context, const ::WordRequest* request, ::WordResponse* response);
    virtual ::grpc::Status GetAllWords(::grpc::ServerContext* context, const ::Empty* request, ::WordList* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_AddWord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AddWord() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_AddWord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddWord(::grpc::ServerContext* /*context*/, const ::WordRequest* /*request*/, ::WordResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAddWord(::grpc::ServerContext* context, ::WordRequest* request, ::grpc::ServerAsyncResponseWriter< ::WordResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetAllWords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetAllWords() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetAllWords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAllWords(::grpc::ServerContext* /*context*/, const ::Empty* /*request*/, ::WordList* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetAllWords(::grpc::ServerContext* context, ::Empty* request, ::grpc::ServerAsyncResponseWriter< ::WordList>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_AddWord<WithAsyncMethod_GetAllWords<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_AddWord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AddWord() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::WordRequest, ::WordResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::WordRequest* request, ::WordResponse* response) { return this->AddWord(context, request, response); }));}
    void SetMessageAllocatorFor_AddWord(
        ::grpc::MessageAllocator< ::WordRequest, ::WordResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::WordRequest, ::WordResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AddWord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddWord(::grpc::ServerContext* /*context*/, const ::WordRequest* /*request*/, ::WordResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AddWord(
      ::grpc::CallbackServerContext* /*context*/, const ::WordRequest* /*request*/, ::WordResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetAllWords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetAllWords() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::Empty, ::WordList>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::Empty* request, ::WordList* response) { return this->GetAllWords(context, request, response); }));}
    void SetMessageAllocatorFor_GetAllWords(
        ::grpc::MessageAllocator< ::Empty, ::WordList>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::Empty, ::WordList>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetAllWords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAllWords(::grpc::ServerContext* /*context*/, const ::Empty* /*request*/, ::WordList* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetAllWords(
      ::grpc::CallbackServerContext* /*context*/, const ::Empty* /*request*/, ::WordList* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_AddWord<WithCallbackMethod_GetAllWords<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_AddWord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AddWord() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_AddWord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddWord(::grpc::ServerContext* /*context*/, const ::WordRequest* /*request*/, ::WordResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetAllWords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetAllWords() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetAllWords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAllWords(::grpc::ServerContext* /*context*/, const ::Empty* /*request*/, ::WordList* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_AddWord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AddWord() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_AddWord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddWord(::grpc::ServerContext* /*context*/, const ::WordRequest* /*request*/, ::WordResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAddWord(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetAllWords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetAllWords() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetAllWords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAllWords(::grpc::ServerContext* /*context*/, const ::Empty* /*request*/, ::WordList* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetAllWords(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AddWord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AddWord() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AddWord(context, request, response); }));
    }
    ~WithRawCallbackMethod_AddWord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddWord(::grpc::ServerContext* /*context*/, const ::WordRequest* /*request*/, ::WordResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AddWord(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetAllWords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetAllWords() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetAllWords(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetAllWords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAllWords(::grpc::ServerContext* /*context*/, const ::Empty* /*request*/, ::WordList* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetAllWords(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AddWord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AddWord() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::WordRequest, ::WordResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::WordRequest, ::WordResponse>* streamer) {
                       return this->StreamedAddWord(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AddWord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AddWord(::grpc::ServerContext* /*context*/, const ::WordRequest* /*request*/, ::WordResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAddWord(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::WordRequest,::WordResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetAllWords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetAllWords() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::Empty, ::WordList>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::Empty, ::WordList>* streamer) {
                       return this->StreamedGetAllWords(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetAllWords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetAllWords(::grpc::ServerContext* /*context*/, const ::Empty* /*request*/, ::WordList* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetAllWords(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Empty,::WordList>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_AddWord<WithStreamedUnaryMethod_GetAllWords<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_AddWord<WithStreamedUnaryMethod_GetAllWords<Service > > StreamedService;
};


#endif  // GRPC_dictionary_2eproto__INCLUDED
